baseURL = 'https://dayiii.com/'
languageCode = 'en-us'
title = 'Day III Digital'
theme = 'PaperMod'
publishDir = 'public'

[params]
    hideFooter = true
    defaultTheme = "dark"
    disableThemeToggle = true
    disableScrollToTop = true
    customCSS = ["css/extended/custom.css"]
    label.icon = "/images/day-iii-logo-header.png"

[[socialIcons]]
    name = "linkedin"
    title = "LinkedIn"
    url = "https://kofi.com"

[[socialIcons]]
    name = "instagram"
    title = "Instagram"
    url = "https://twitter.com"

[[menu.main]]
    name = "Services"
    url = "/#services"
    weight = 3

[[menu.main]]
    name = "Clients"
    url = "/#clients"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 6

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true